### ISSUE TITLE
Ensure that Docker Alexandria installation works for users

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#11]

**Comment by rhdekker** [comment]
I discussed this with Bram today. He will update the Docker image in the Docker hub and he will update the installation instructions. The use of Docker Compose will be required (which is part of the default Docker installation).

**Comment by djbpitt** [comment]
Thank you for the update! I'll try it again (= may require installation
instructions) whenever it's ready. My assistants have both installed Docker
(one on Windows 10, one on Mac) and stand ready to try, as well.

**Comment by rhdekker** [comment]
Bram has updated the Alexandria Docker images. You can install all the images simultaneously using one Docker compose file.
Bram has written documentation on how to do that in the Readme.md file of the Alexandria Workshops Notebook project on Github, which you can find here:  
https://github.com/HuygensING/alexandria-workshop-notebooks

Not all documentation in the Readme.md file is relevant for docker compose. You only need to do the steps listed under the header 
"run the alexandria-markup-notebook + dependencies using docker-compose”

**Comment by djbpitt** [comment]
Seems to work
