### ISSUE TITLE
Update bibliography

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#43]
- [x] Merge 2019 application bibliography into general/references.md (@djbpitt)
- [x] Review bibliography (@bleekere)

**Comment by djbpitt** [comment]
@bleekere I’ve integrated the bibliographic entries from our 2019 application in our references list. Since you’re the one of us who is most up to date on relevant bibliography, could you please review it when you have a chance, and then slide it over to the “Done” column?

**Comment by bleekere** [comment]
I updated and reviewed the references and checked for consistency in style. Should be ok now.

**Comment by djbpitt** [comment]
Thank you, Elli!
