### ISSUE TITLE
Update exemplary projects

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#44]
- [x] Update exemplary projects at general/exemplary_editions.md (@djbpitt)
- [x] Review updates (@bleekere)

**Comment by djbpitt** [comment]
Ready for review by @bleekere, after which it can be moved to “Done”.

**Comment by bleekere** [comment]
I've reviewed the exemplary projects (which was a fun task! no sarcasm here) and updated the list.

**Comment by djbpitt** [comment]
@bleekere Thank you, Elli!
