### ISSUE TITLE
Review and update RDF/LOD

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#52]

**Comment by gabikeane** [comment]
David and I both became confused when we got to the Complications/IRs and NIRs section. If a resource is a non-web resource, why would one need to use a 303 redirect for an NIR if we're already assigning it a URI like we do for an IR? @hcayless could you elaborate on why a redirect is necessary when an NIR has an existing URI.

Secondly, what do you mean by the point "Punning" as an option for NIRs? Are we missing something that should be obvious?
