### ISSUE TITLE
Python notebooks

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#6]
Should we use `with` for opening files, and not just `open`? If we use `open`, should we also specify `close`?

**Comment by rhdekker** [comment]
iMO with should always be used. It is not harder to learn and it is much better way working. It makes people aware that file handles are limited resources that should be handled with care.

**Comment by narae-student** [comment]
All I ever show is something like
txt = open('textfile.txt').read()

That way, closing is not needed.  Instilling people the importance of closing file is/should be done while learning how to write out, which I don't think I will teach during Python Clinic. That is, it's someone else's cross to bear!

**Comment by djbpitt** [comment]
Resolved:` open()` in week one, `with` in week 2
