### ISSUE TITLE
PyCharm installation? Is there further Python instruction being planned?

### ISSUE THREAD

**Issue by narae-student** [Pittsburgh-NEH-Institute/Institute-Materials-2017#8]
I see that installing PyCharm is requested on all users in the "Before You Arrive" document. Questions:

1. Is there additional Python-based instruction being planned in Week 2 or Week 3, which uses PyCharm?

2. If the answer is no and my two Python sessions in Week 1 are all there is, then is it necessary to require installation of PyCharm? 

3. If the answer to 1. is yes, then could the XML-related content you proposed for my sessions be pushed into one of the later sessions? The more I think about it, fitting in another mini lesson on processing XML in my Python Clinic 2 feels unrealistic.

**Comment by djbpitt** [comment]
Ad 1 et 2: I'd like to include PyCharm in Week 2 Python work, such as with collation. The participants can do that work in a Jupyter notebook, but the more complex their tasks, the more they'll benefit from using a more powerful IDE. But we haven't finished drafting Week 2 yet, so this could change.

Ad 3: We can do "wrangling XML in Python" as a separate session. I've written separately to suggest that we resurrect that free time on Wednesday and Friday afternoons, and one of the resurrected sessions could be about XML in Python. I'm drafting that now, and I'll push it as soon as it's sufficiently far along to be worth a look.
