### ISSUE TITLE
Write XQuery materials

### ISSUE THREAD

**Issue by gabikeane** [Pittsburgh-NEH-Institute/Institute-Materials-2017#82]
Introductory XQuery materials for Friday of Week 2

**Comment by gabikeane** [comment]
Wednesday: review XQuery 1 and 2, consider whether we need a third lesson for week 3?

**Comment by djbpitt** [comment]
@gabikeane I’ve revised XQuery 2; it's ready for you to review.

**Comment by djbpitt** [comment]
@gabikeane I’ve just revised XQuery 1, as well, so that’s also ready for your review. There’s a note in their about an example that we should revisit, but we should also look it over more generally.

**Comment by gabikeane** [comment]
XQuery 1 and 2 reviewed and edited, will review XQuery 3 when complete
